spring.application.name=spring-ai-ollama-openai-1
server.port=8081
# spring.ai.chat.client.enabled=false  
#So it  should not create bean automatically

#spring.ai.openai.base-url=http://localhost:4891
#spring.ai.openai.api-key=dummy
#spring.ai.openai.chat.options.model=gpt4all-DeepSeek-R1-Distill-Qwen-7B

# spring.ai.ollama.base-url = http://localhost:11434
# spring.ai.ollama.chat.options.model=deepseek-r1:latest
# spring.ai.ollama.chat.options.temperature=0.7
